// This file is generated by RustQ. Do not edit by hand.

#[rustler::nif(schedule = "DirtyCpu")]
fn parse_sfc_nif<'a>(env: Env<'a>, source: &str) -> NifResult<Term<'a>> {
    parse_sfc_nif_impl(env, source)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn analyze_sfc_nif<'a>(env: Env<'a>, source: &str, mode: &str) -> NifResult<Term<'a>> {
    analyze_sfc_nif_impl(env, source, mode)
}
#[allow(clippy::too_many_arguments)]
#[rustler::nif(schedule = "DirtyCpu")]
fn compile_sfc_nif<'a>(
    env: Env<'a>,
    source: &str,
    opts: CompileSfcOpts,
) -> NifResult<Term<'a>> {
    compile_sfc_nif_impl(env, source, opts)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn sfc_template_assets_nif<'a>(
    env: Env<'a>,
    source: &str,
    filename: &str,
) -> NifResult<Term<'a>> {
    sfc_template_assets_nif_impl(env, source, filename)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn rewrite_sfc_template_assets_nif<'a>(
    env: Env<'a>,
    code: &str,
    assets: Vec<(String, String)>,
) -> NifResult<Term<'a>> {
    rewrite_sfc_template_assets_nif_impl(env, code, assets)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn sfc_scope_id_nif<'a>(
    env: Env<'a>,
    filename: &str,
    opts: ScopeIdOpts,
) -> NifResult<Term<'a>> {
    sfc_scope_id_nif_impl(env, filename, opts)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn compile_template_nif<'a>(
    env: Env<'a>,
    source: &str,
    opts: CompileTemplateOpts,
) -> NifResult<Term<'a>> {
    compile_template_nif_impl(env, source, opts)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn compile_ssr_nif<'a>(env: Env<'a>, source: &str) -> NifResult<Term<'a>> {
    compile_ssr_nif_impl(env, source)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn compile_vapor_nif<'a>(
    env: Env<'a>,
    source: &str,
    opts: CompileVaporOpts,
) -> NifResult<Term<'a>> {
    compile_vapor_nif_impl(env, source, opts)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn vapor_ir_nif<'a>(env: Env<'a>, source: &str) -> NifResult<Term<'a>> {
    vapor_ir_nif_impl(env, source)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn lint_nif<'a>(env: Env<'a>, source: &str, filename: &str) -> NifResult<Term<'a>> {
    lint_nif_impl(env, source, filename)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn select_css_nif<'a>(
    env: Env<'a>,
    source: &str,
    opts: ParseCssOpts,
    selector_term: Term<'a>,
) -> NifResult<Term<'a>> {
    select_css_nif_impl(env, source, opts, selector_term)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn parse_css_ast_nif<'a>(
    env: Env<'a>,
    source: &str,
    opts: ParseCssOpts,
) -> NifResult<Term<'a>> {
    parse_css_ast_nif_impl(env, source, opts)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn print_css_ast_nif<'a>(
    env: Env<'a>,
    ast: Term<'a>,
    opts: PrintCssOpts,
) -> NifResult<Term<'a>> {
    print_css_ast_nif_impl(env, ast, opts)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn compile_sass_nif<'a>(
    env: Env<'a>,
    source: &str,
    opts: CompileSassOpts,
) -> NifResult<Term<'a>> {
    compile_sass_nif_impl(env, source, opts)
}
#[allow(clippy::too_many_arguments)]
#[rustler::nif(schedule = "DirtyCpu")]
fn compile_css_nif<'a>(
    env: Env<'a>,
    source: &str,
    opts: CompileCssOpts,
) -> NifResult<Term<'a>> {
    compile_css_nif_impl(env, source, opts)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn bundle_css_nif<'a>(
    env: Env<'a>,
    entry_path: &str,
    opts: BundleCssOpts,
) -> NifResult<Term<'a>> {
    bundle_css_nif_impl(env, entry_path, opts)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn split_template_nif<'a>(
    env: Env<'a>,
    source: &str,
    opts: SplitTemplateOpts,
) -> NifResult<Term<'a>> {
    split_template_nif_impl(env, source, opts)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn generate_dts_nif<'a>(
    env: Env<'a>,
    source: &str,
    filename: &str,
) -> NifResult<Term<'a>> {
    generate_dts_nif_impl(env, source, filename)
}
