// This file is generated by RustQ. Do not edit by hand.

impl rustler::Encoder for EncodedLoc {
    fn encode<'a>(&self, env: rustler::Env<'a>) -> rustler::Term<'a> {
        Term::map_from_arrays(
                env,
                &[
                    atoms::start().encode(env),
                    atoms::end_().encode(env),
                    atoms::start_line().encode(env),
                    atoms::start_column().encode(env),
                    atoms::end_line().encode(env),
                    atoms::end_column().encode(env),
                ],
                &[
                    self.start.encode(env),
                    self.end.encode(env),
                    self.start_line.encode(env),
                    self.start_column.encode(env),
                    self.end_line.encode(env),
                    self.end_column.encode(env),
                ],
            )
            .unwrap()
    }
}
impl rustler::Encoder for EncodedLintDiagnostic<'_> {
    fn encode<'a>(&self, env: rustler::Env<'a>) -> rustler::Term<'a> {
        Term::map_from_arrays(
                env,
                &[atoms::message().encode(env), atoms::name().encode(env)],
                &[self.message.encode(env), self.name.encode(env)],
            )
            .unwrap()
    }
}
