// This file is generated by RustQ. Do not edit by hand.

mod atoms {
    rustler::atoms! {
        ok, error, template, script, script_setup, styles, custom_blocks, content, lang,
        scoped, module, setup, attrs, block_type, loc, start, end_ = "end", start_line,
        start_column, end_line, end_column, code, css, errors, warnings, template_hash,
        style_hash, script_hash, macro_artifacts, message, preamble, helpers, templates,
        root, block, operations, effects, returns, element, key, values, value,
        condition, positive, negative, source, index, render, once, parent, anchor,
        key_prop, tag, props, slots, name, fallback, delegate, effect, modifiers, camel,
        prop_modifier, is_component, components, directives, kind, asset, dynamic_slots,
        child_id, parent_id, offset, ast, map, css_vars, exports, minify, targets,
        scope_id, filename_opt, custom_media, static_, element_template_map, set_prop,
        set_dynamic_props, set_text, set_event, set_html, set_template_ref, insert_node,
        prepend_node, directive, if_node, for_node, create_component, slot_outlet,
        get_text_child, child_ref, next_ref, statics, dts, v_show, v_model, regular,
        teleport, keep_alive, suspense, dynamic,
    }
}
