// This file is generated by RustQ. Do not edit by hand.

mod atoms {
    rustler::atoms! {
        r#for = "for", r#if = "if", anchor, asset, ast, attrs, bindings, block,
        block_type, builtin, camel, capture, child_id, child_ref, children, code, column,
        component, component_usages, components, condition, content, context, control,
        create_component, css, css_import, css_url, css_vars, custom_blocks, delegate,
        diagnostics, directive, directives, dts, dynamic, dynamic_slots, effect, effects,
        element, element_template_map, emits, end_ = "end", end_column, end_line, error,
        errors, events, exports, expression, fallback, flags, fn_exp, for_node,
        get_text_child, group, handler, has_scoped, has_spread_attrs, helpers, id,
        if_node, index, input_type, insert_node, is_component, is_dynamic, is_element,
        is_event, is_expr, keep_alive, key, key_prop, keys, kind, lang, line, loc,
        location, macro_artifacts, match_scope, media, message, model_modifiers,
        model_update, models, modifiers, module, name, negative, next_ref, non_keys,
        object, offset, ok, once, only_child, operations, options, parent, parent_id,
        passive, positive, preamble, prepend_node, prop_modifier, props, range,
        recoverable, ref_for, regular, render, required, returns, scoped, script,
        script_hash, script_setup, set_dynamic_props, set_event, set_html,
        set_merged_props, set_prop, set_template_ref, set_text, setup,
        should_force_reload, slot_outlet, slots, slotted, source, source_map, sources,
        src, start, start_column, start_line, static_, statics, stats, style_hash,
        styles, supports, suspense, tag, teleport, temp_id, template,
        template_expressions, template_hash, templates, transition, transition_group,
        undefined_refs, url, used_components, used_directives, v_model, v_show, value,
        value_kind, values, var_name, warnings
    }
}
