// This file is generated by RustQ. Do not edit by hand.

impl rustler::Encoder for EncodedLoc {
    fn encode<'a>(&self, env: rustler::Env<'a>) -> rustler::Term<'a> {
        Term::map_from_arrays(
                env,
                &[
                    atoms::start().encode(env),
                    atoms::end_().encode(env),
                    atoms::start_line().encode(env),
                    atoms::start_column().encode(env),
                    atoms::end_line().encode(env),
                    atoms::end_column().encode(env),
                ],
                &[
                    self.start.encode(env),
                    self.end.encode(env),
                    self.start_line.encode(env),
                    self.start_column.encode(env),
                    self.end_line.encode(env),
                    self.end_column.encode(env),
                ],
            )
            .unwrap()
    }
}
impl rustler::Encoder for EncodedLintDiagnostic<'_> {
    fn encode<'a>(&self, env: rustler::Env<'a>) -> rustler::Term<'a> {
        Term::map_from_arrays(
                env,
                &[atoms::message().encode(env), atoms::name().encode(env)],
                &[self.message.encode(env), self.name.encode(env)],
            )
            .unwrap()
    }
}
impl rustler::Encoder for EncodedSfcError<'_> {
    fn encode<'a>(&self, env: rustler::Env<'a>) -> rustler::Term<'a> {
        let mut keys = vec![atoms::message().encode(env)];
        let mut values = vec![self.message.encode(env)];
        if let Some(value) = self.code.as_ref() {
            keys.push(atoms::code().encode(env));
            values.push(value.encode(env));
        }
        Term::map_from_arrays(env, &keys, &values).unwrap()
    }
}
impl rustler::Encoder for EncodedTemplateBlock<'_> {
    fn encode<'a>(&self, env: rustler::Env<'a>) -> rustler::Term<'a> {
        Term::map_from_arrays(
                env,
                &[
                    atoms::content().encode(env),
                    atoms::lang().encode(env),
                    atoms::loc().encode(env),
                    atoms::attrs().encode(env),
                ],
                &[
                    self.0.content.as_ref().encode(env),
                    self.0.lang.as_deref().encode(env),
                    loc_to_term(env, &self.0.loc),
                    attrs_to_term(env, &self.0.attrs),
                ],
            )
            .unwrap()
    }
}
impl rustler::Encoder for EncodedScriptBlock<'_> {
    fn encode<'a>(&self, env: rustler::Env<'a>) -> rustler::Term<'a> {
        Term::map_from_arrays(
                env,
                &[
                    atoms::content().encode(env),
                    atoms::lang().encode(env),
                    atoms::setup().encode(env),
                    atoms::loc().encode(env),
                    atoms::attrs().encode(env),
                ],
                &[
                    self.0.content.as_ref().encode(env),
                    self.0.lang.as_deref().encode(env),
                    self.0.setup.encode(env),
                    loc_to_term(env, &self.0.loc),
                    attrs_to_term(env, &self.0.attrs),
                ],
            )
            .unwrap()
    }
}
impl rustler::Encoder for EncodedStyleBlock<'_> {
    fn encode<'a>(&self, env: rustler::Env<'a>) -> rustler::Term<'a> {
        Term::map_from_arrays(
                env,
                &[
                    atoms::content().encode(env),
                    atoms::lang().encode(env),
                    atoms::scoped().encode(env),
                    atoms::module().encode(env),
                    atoms::loc().encode(env),
                    atoms::attrs().encode(env),
                ],
                &[
                    self.0.content.as_ref().encode(env),
                    self.0.lang.as_deref().encode(env),
                    self.0.scoped.encode(env),
                    self.0.module.as_deref().encode(env),
                    loc_to_term(env, &self.0.loc),
                    attrs_to_term(env, &self.0.attrs),
                ],
            )
            .unwrap()
    }
}
impl rustler::Encoder for EncodedCustomBlock<'_> {
    fn encode<'a>(&self, env: rustler::Env<'a>) -> rustler::Term<'a> {
        Term::map_from_arrays(
                env,
                &[
                    atoms::block_type().encode(env),
                    atoms::content().encode(env),
                    atoms::loc().encode(env),
                    atoms::attrs().encode(env),
                ],
                &[
                    self.0.block_type.as_ref().encode(env),
                    self.0.content.as_ref().encode(env),
                    loc_to_term(env, &self.0.loc),
                    attrs_to_term(env, &self.0.attrs),
                ],
            )
            .unwrap()
    }
}
impl rustler::Encoder for EncodedMacroArtifact<'_> {
    fn encode<'a>(&self, env: rustler::Env<'a>) -> rustler::Term<'a> {
        let mut keys = vec![
            atoms::kind().encode(env), atoms::name().encode(env), atoms::source()
            .encode(env), atoms::content().encode(env), atoms::start().encode(env),
            atoms::end_().encode(env)
        ];
        let mut values = vec![
            self.0.kind.as_str().encode(env), self.0.name.as_str().encode(env), self.0
            .source.as_str().encode(env), self.0.content.as_str().encode(env), self.0
            .start.encode(env), self.0.end.encode(env)
        ];
        if let Some(value) = self.0.module_code.as_ref() {
            keys.push(atoms::code().encode(env));
            values.push(value.as_str().encode(env));
        }
        Term::map_from_arrays(env, &keys, &values).unwrap()
    }
}
impl rustler::Encoder for EncodedTemplateCompileResult<'_> {
    fn encode<'a>(&self, env: rustler::Env<'a>) -> rustler::Term<'a> {
        Term::map_from_arrays(
                env,
                &[
                    atoms::code().encode(env),
                    atoms::preamble().encode(env),
                    atoms::helpers().encode(env),
                ],
                &[
                    self.code.encode(env),
                    self.preamble.encode(env),
                    self.helpers.encode(env),
                ],
            )
            .unwrap()
    }
}
impl rustler::Encoder for EncodedSsrCompileResult<'_> {
    fn encode<'a>(&self, env: rustler::Env<'a>) -> rustler::Term<'a> {
        Term::map_from_arrays(
                env,
                &[atoms::code().encode(env), atoms::preamble().encode(env)],
                &[self.code.encode(env), self.preamble.encode(env)],
            )
            .unwrap()
    }
}
