// This file is generated by RustQ. Do not edit by hand.

#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedBinding {
    pub name: String,
    pub kind: String,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedComponentUsage {
    pub name: String,
    pub props: Vec<EncodedPassedProp>,
    pub events: Vec<EncodedEventListener>,
    pub has_spread_attrs: bool,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedDiagnostic {
    pub code: Option<String>,
    pub message: String,
    pub recoverable: bool,
    pub location: Option<EncodedSourceLocation>,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedDts {
    pub dts: String,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedEventListener {
    pub name: String,
    pub handler: Option<String>,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedLoc {
    pub start: usize,
    pub end: usize,
    pub start_line: usize,
    pub start_column: usize,
    pub end_line: usize,
    pub end_column: usize,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedPassedProp {
    pub name: String,
    pub value: Option<String>,
    pub is_dynamic: bool,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedPosition {
    pub offset: u32,
    pub line: u32,
    pub column: u32,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedPropDeclaration {
    pub name: String,
    pub required: bool,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedRange {
    pub start: u32,
    pub end: u32,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedSass {
    pub code: String,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedSfcAnalysis {
    pub stats: EncodedSfcStats,
    pub bindings: Vec<EncodedBinding>,
    pub props: Vec<EncodedPropDeclaration>,
    pub emits: Vec<String>,
    pub models: Vec<String>,
    pub used_components: Vec<String>,
    pub used_directives: Vec<String>,
    pub undefined_refs: Vec<EncodedUndefinedRef>,
    pub component_usages: Vec<EncodedComponentUsage>,
    pub template_expressions: Vec<EncodedTemplateExpression>,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedSfcStats {
    pub bindings: usize,
    pub props: usize,
    pub emits: usize,
    pub models: usize,
    pub used_components: usize,
    pub used_directives: usize,
    pub undefined_refs: usize,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedSourceLocation {
    pub start: EncodedPosition,
    pub end: EncodedPosition,
    pub source: String,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedTemplateAsset {
    pub url: String,
    pub var_name: String,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedTemplateExpression {
    pub source: String,
    pub kind: String,
    pub range: EncodedRange,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedUndefinedRef {
    pub name: String,
    pub offset: u32,
    pub context: String,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedVaporDiagnosticsOutput {
    pub code: String,
    pub templates: Vec<String>,
    pub diagnostics: Vec<EncodedDiagnostic>,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedVaporIr<'a> {
    pub templates: Vec<String>,
    pub components: Vec<String>,
    pub directives: Vec<String>,
    pub block: Term<'a>,
    pub element_template_map: Vec<(usize, usize)>,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedVaporOutput {
    pub code: String,
    pub templates: Vec<String>,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedVaporSplit<'a> {
    pub statics: Vec<String>,
    pub slots: Vec<Term<'a>>,
    pub templates: Vec<String>,
    pub element_template_map: Vec<(usize, usize)>,
}
