// This file is generated by RustQ. Do not edit by hand.

pub(crate) fn encode_block_location<'a>(
    env: rustler::Env<'a>,
    value: &BlockLocation,
) -> rustler::Term<'a> {
    rustler::Term::map_from_arrays(
            env,
            &[
                atoms::start().encode(env),
                atoms::end().encode(env),
                atoms::tag_start().encode(env),
                atoms::tag_end().encode(env),
                atoms::start_line().encode(env),
                atoms::start_column().encode(env),
                atoms::end_line().encode(env),
                atoms::end_column().encode(env),
            ],
            &[
                value.start.encode(env),
                value.end.encode(env),
                value.tag_start.encode(env),
                value.tag_end.encode(env),
                value.start_line.encode(env),
                value.start_column.encode(env),
                value.end_line.encode(env),
                value.end_column.encode(env),
            ],
        )
        .unwrap()
}
