// This file is generated by RustQ. Do not edit by hand.

pub(crate) fn encode_block_ir_node<'a>(
    env: rustler::Env<'a>,
    value: &BlockIRNode<'_>,
) -> rustler::Term<'a> {
    rustler::Term::map_from_arrays(
            env,
            &[
                atoms::dynamic().encode(env),
                atoms::temp_id().encode(env),
                atoms::effects().encode(env),
                atoms::operations().encode(env),
                atoms::returns().encode(env),
            ],
            &[
                encode_ir_dynamic_info(env, &value.dynamic),
                value.temp_id.encode(env),
                value
                    .effect
                    .iter()
                    .map(|item0| encode_ir_effect(env, item0))
                    .collect::<Vec<rustler::Term<'a>>>()
                    .encode(env),
                value
                    .operation
                    .iter()
                    .map(|item0| encode_operation_node(env, item0))
                    .collect::<Vec<rustler::Term<'a>>>()
                    .encode(env),
                value
                    .returns
                    .iter()
                    .map(|item0| item0.encode(env))
                    .collect::<Vec<rustler::Term<'a>>>()
                    .encode(env),
            ],
        )
        .unwrap()
}
pub(crate) fn encode_ir_dynamic_info<'a>(
    env: rustler::Env<'a>,
    value: &IRDynamicInfo<'_>,
) -> rustler::Term<'a> {
    rustler::Term::map_from_arrays(
            env,
            &[
                atoms::flags().encode(env),
                atoms::children().encode(env),
                atoms::id().encode(env),
            ],
            &[
                value.flags.encode(env),
                value
                    .children
                    .iter()
                    .map(|item0| encode_ir_dynamic_info(env, item0))
                    .collect::<Vec<rustler::Term<'a>>>()
                    .encode(env),
                value
                    .id
                    .as_ref()
                    .map(|item0| item0.encode(env))
                    .unwrap_or_else(|| rustler::types::atom::nil().encode(env)),
            ],
        )
        .unwrap()
}
pub(crate) fn encode_ir_effect<'a>(
    env: rustler::Env<'a>,
    value: &IREffect<'_>,
) -> rustler::Term<'a> {
    value
        .operations
        .iter()
        .map(|item0| encode_operation_node(env, item0))
        .collect::<Vec<rustler::Term<'a>>>()
        .encode(env)
}
pub(crate) fn encode_operation_node<'a>(
    env: rustler::Env<'a>,
    value: &OperationNode<'_>,
) -> rustler::Term<'a> {
    match value {
        OperationNode::SetProp(field0) => {
            encode_set_prop_ir_node(env, field0)
                .map_put(atoms::kind().encode(env), atoms::set_prop().encode(env))
                .unwrap()
        }
        OperationNode::SetDynamicProps(field0) => {
            encode_set_dynamic_props_ir_node(env, field0)
                .map_put(
                    atoms::kind().encode(env),
                    atoms::set_dynamic_props().encode(env),
                )
                .unwrap()
        }
        OperationNode::SetMergedProps(field0) => {
            encode_set_merged_props_ir_node(env, field0)
                .map_put(
                    atoms::kind().encode(env),
                    atoms::set_merged_props().encode(env),
                )
                .unwrap()
        }
        OperationNode::SetText(field0) => {
            encode_set_text_ir_node(env, field0)
                .map_put(atoms::kind().encode(env), atoms::set_text().encode(env))
                .unwrap()
        }
        OperationNode::SetEvent(field0) => {
            encode_set_event_ir_node(env, field0)
                .map_put(atoms::kind().encode(env), atoms::set_event().encode(env))
                .unwrap()
        }
        OperationNode::SetHtml(field0) => {
            encode_set_html_ir_node(env, field0)
                .map_put(atoms::kind().encode(env), atoms::set_html().encode(env))
                .unwrap()
        }
        OperationNode::SetTemplateRef(field0) => {
            encode_set_template_ref_ir_node(env, field0)
                .map_put(
                    atoms::kind().encode(env),
                    atoms::set_template_ref().encode(env),
                )
                .unwrap()
        }
        OperationNode::InsertNode(field0) => {
            encode_insert_node_ir_node(env, field0)
                .map_put(atoms::kind().encode(env), atoms::insert_node().encode(env))
                .unwrap()
        }
        OperationNode::PrependNode(field0) => {
            encode_prepend_node_ir_node(env, field0)
                .map_put(atoms::kind().encode(env), atoms::prepend_node().encode(env))
                .unwrap()
        }
        OperationNode::Directive(field0) => {
            encode_directive_ir_node(env, field0)
                .map_put(atoms::kind().encode(env), atoms::directive().encode(env))
                .unwrap()
        }
        OperationNode::If(field0) => {
            encode_if_ir_node(env, field0)
                .map_put(atoms::kind().encode(env), atoms::if_node().encode(env))
                .unwrap()
        }
        OperationNode::For(field0) => {
            encode_for_ir_node(env, field0)
                .map_put(atoms::kind().encode(env), atoms::for_node().encode(env))
                .unwrap()
        }
        OperationNode::CreateComponent(field0) => {
            encode_create_component_ir_node(env, field0)
                .map_put(
                    atoms::kind().encode(env),
                    atoms::create_component().encode(env),
                )
                .unwrap()
        }
        OperationNode::SlotOutlet(field0) => {
            encode_slot_outlet_ir_node(env, field0)
                .map_put(atoms::kind().encode(env), atoms::slot_outlet().encode(env))
                .unwrap()
        }
        OperationNode::GetTextChild(field0) => {
            encode_get_text_child_ir_node(env, field0)
                .map_put(atoms::kind().encode(env), atoms::get_text_child().encode(env))
                .unwrap()
        }
        OperationNode::ChildRef(field0) => {
            encode_child_ref_ir_node(env, field0)
                .map_put(atoms::kind().encode(env), atoms::child_ref().encode(env))
                .unwrap()
        }
        OperationNode::NextRef(field0) => {
            encode_next_ref_ir_node(env, field0)
                .map_put(atoms::kind().encode(env), atoms::next_ref().encode(env))
                .unwrap()
        }
    }
}
pub(crate) fn encode_set_prop_ir_node<'a>(
    env: rustler::Env<'a>,
    value: &SetPropIRNode<'_>,
) -> rustler::Term<'a> {
    rustler::Term::map_from_arrays(
            env,
            &[
                atoms::element().encode(env),
                atoms::value().encode(env),
                atoms::tag().encode(env),
                atoms::camel().encode(env),
                atoms::prop_modifier().encode(env),
            ],
            &[
                value.element.encode(env),
                encode_ir_prop(env, &value.prop),
                value.tag.encode(env),
                value.camel.encode(env),
                value.prop_modifier.encode(env),
            ],
        )
        .unwrap()
}
pub(crate) fn encode_set_dynamic_props_ir_node<'a>(
    env: rustler::Env<'a>,
    value: &SetDynamicPropsIRNode<'_>,
) -> rustler::Term<'a> {
    rustler::Term::map_from_arrays(
            env,
            &[
                atoms::element().encode(env),
                atoms::props().encode(env),
                atoms::is_event().encode(env),
            ],
            &[
                value.element.encode(env),
                value
                    .props
                    .iter()
                    .map(|item0| encode_simple_expr(env, item0))
                    .collect::<Vec<rustler::Term<'a>>>()
                    .encode(env),
                value.is_event.encode(env),
            ],
        )
        .unwrap()
}
pub(crate) fn encode_set_merged_props_ir_node<'a>(
    env: rustler::Env<'a>,
    value: &SetMergedPropsIRNode<'_>,
) -> rustler::Term<'a> {
    rustler::Term::map_from_arrays(
            env,
            &[atoms::element().encode(env), atoms::sources().encode(env)],
            &[
                value.element.encode(env),
                value
                    .sources
                    .iter()
                    .map(|item0| encode_merged_props_source(env, item0))
                    .collect::<Vec<rustler::Term<'a>>>()
                    .encode(env),
            ],
        )
        .unwrap()
}
pub(crate) fn encode_set_text_ir_node<'a>(
    env: rustler::Env<'a>,
    value: &SetTextIRNode<'_>,
) -> rustler::Term<'a> {
    rustler::Term::map_from_arrays(
            env,
            &[
                atoms::element().encode(env),
                atoms::is_element().encode(env),
                atoms::values().encode(env),
            ],
            &[
                value.element.encode(env),
                value.is_element.encode(env),
                value
                    .values
                    .iter()
                    .map(|item0| encode_simple_expr(env, item0))
                    .collect::<Vec<rustler::Term<'a>>>()
                    .encode(env),
            ],
        )
        .unwrap()
}
pub(crate) fn encode_set_event_ir_node<'a>(
    env: rustler::Env<'a>,
    value: &SetEventIRNode<'_>,
) -> rustler::Term<'a> {
    rustler::Term::map_from_arrays(
            env,
            &[
                atoms::element().encode(env),
                atoms::key().encode(env),
                atoms::value().encode(env),
                atoms::modifiers().encode(env),
                atoms::delegate().encode(env),
                atoms::effect().encode(env),
            ],
            &[
                value.element.encode(env),
                encode_simple_expr(env, &value.key),
                value
                    .value
                    .as_ref()
                    .map(|item0| encode_simple_expr(env, item0))
                    .unwrap_or_else(|| rustler::types::atom::nil().encode(env)),
                encode_event_modifiers(env, &value.modifiers),
                value.delegate.encode(env),
                value.effect.encode(env),
            ],
        )
        .unwrap()
}
pub(crate) fn encode_set_html_ir_node<'a>(
    env: rustler::Env<'a>,
    value: &SetHtmlIRNode<'_>,
) -> rustler::Term<'a> {
    rustler::Term::map_from_arrays(
            env,
            &[atoms::element().encode(env), atoms::value().encode(env)],
            &[value.element.encode(env), encode_simple_expr(env, &value.value)],
        )
        .unwrap()
}
pub(crate) fn encode_set_template_ref_ir_node<'a>(
    env: rustler::Env<'a>,
    value: &SetTemplateRefIRNode<'_>,
) -> rustler::Term<'a> {
    rustler::Term::map_from_arrays(
            env,
            &[
                atoms::element().encode(env),
                atoms::value().encode(env),
                atoms::ref_for().encode(env),
            ],
            &[
                value.element.encode(env),
                encode_simple_expr(env, &value.value),
                value.ref_for.encode(env),
            ],
        )
        .unwrap()
}
pub(crate) fn encode_insert_node_ir_node<'a>(
    env: rustler::Env<'a>,
    value: &InsertNodeIRNode<'_>,
) -> rustler::Term<'a> {
    rustler::Term::map_from_arrays(
            env,
            &[
                atoms::element().encode(env),
                atoms::parent().encode(env),
                atoms::anchor().encode(env),
            ],
            &[
                value
                    .elements
                    .iter()
                    .map(|item0| item0.encode(env))
                    .collect::<Vec<rustler::Term<'a>>>()
                    .encode(env),
                value.parent.encode(env),
                value
                    .anchor
                    .as_ref()
                    .map(|item0| item0.encode(env))
                    .unwrap_or_else(|| rustler::types::atom::nil().encode(env)),
            ],
        )
        .unwrap()
}
pub(crate) fn encode_prepend_node_ir_node<'a>(
    env: rustler::Env<'a>,
    value: &PrependNodeIRNode<'_>,
) -> rustler::Term<'a> {
    rustler::Term::map_from_arrays(
            env,
            &[atoms::element().encode(env), atoms::parent().encode(env)],
            &[
                value
                    .elements
                    .iter()
                    .map(|item0| item0.encode(env))
                    .collect::<Vec<rustler::Term<'a>>>()
                    .encode(env),
                value.parent.encode(env),
            ],
        )
        .unwrap()
}
pub(crate) fn encode_directive_ir_node<'a>(
    env: rustler::Env<'a>,
    value: &DirectiveIRNode<'_>,
) -> rustler::Term<'a> {
    rustler::Term::map_from_arrays(
            env,
            &[
                atoms::element().encode(env),
                atoms::value().encode(env),
                atoms::name().encode(env),
                atoms::builtin().encode(env),
                atoms::tag().encode(env),
                atoms::input_type().encode(env),
            ],
            &[
                value.element.encode(env),
                encode_directive_expression(env, &value.dir),
                value.name.encode(env),
                value.builtin.encode(env),
                value.tag.encode(env),
                value.input_type.encode(env),
            ],
        )
        .unwrap()
}
pub(crate) fn encode_if_ir_node<'a>(
    env: rustler::Env<'a>,
    value: &IfIRNode<'_>,
) -> rustler::Term<'a> {
    rustler::Term::map_from_arrays(
            env,
            &[
                atoms::id().encode(env),
                atoms::condition().encode(env),
                atoms::positive().encode(env),
                atoms::negative().encode(env),
                atoms::once().encode(env),
                atoms::parent().encode(env),
                atoms::anchor().encode(env),
            ],
            &[
                value.id.encode(env),
                encode_simple_expr(env, &value.condition),
                encode_block_ir_node(env, &value.positive),
                value
                    .negative
                    .as_ref()
                    .map(|item0| encode_negative_branch(env, item0))
                    .unwrap_or_else(|| rustler::types::atom::nil().encode(env)),
                value.once.encode(env),
                value
                    .parent
                    .as_ref()
                    .map(|item0| item0.encode(env))
                    .unwrap_or_else(|| rustler::types::atom::nil().encode(env)),
                value
                    .anchor
                    .as_ref()
                    .map(|item0| encode_insertion_anchor(env, item0))
                    .unwrap_or_else(|| rustler::types::atom::nil().encode(env)),
            ],
        )
        .unwrap()
}
pub(crate) fn encode_for_ir_node<'a>(
    env: rustler::Env<'a>,
    value: &ForIRNode<'_>,
) -> rustler::Term<'a> {
    rustler::Term::map_from_arrays(
            env,
            &[
                atoms::id().encode(env),
                atoms::source().encode(env),
                atoms::value().encode(env),
                atoms::key().encode(env),
                atoms::index().encode(env),
                atoms::key_prop().encode(env),
                atoms::render().encode(env),
                atoms::once().encode(env),
                atoms::component().encode(env),
                atoms::only_child().encode(env),
                atoms::parent().encode(env),
                atoms::anchor().encode(env),
                atoms::match_scope().encode(env),
            ],
            &[
                value.id.encode(env),
                encode_simple_expr(env, &value.source),
                value
                    .value
                    .as_ref()
                    .map(|item0| encode_simple_expr(env, item0))
                    .unwrap_or_else(|| rustler::types::atom::nil().encode(env)),
                value
                    .key
                    .as_ref()
                    .map(|item0| encode_simple_expr(env, item0))
                    .unwrap_or_else(|| rustler::types::atom::nil().encode(env)),
                value
                    .index
                    .as_ref()
                    .map(|item0| encode_simple_expr(env, item0))
                    .unwrap_or_else(|| rustler::types::atom::nil().encode(env)),
                value
                    .key_prop
                    .as_ref()
                    .map(|item0| encode_simple_expr(env, item0))
                    .unwrap_or_else(|| rustler::types::atom::nil().encode(env)),
                encode_block_ir_node(env, &value.render),
                value.once.encode(env),
                value.component.encode(env),
                value.only_child.encode(env),
                value
                    .parent
                    .as_ref()
                    .map(|item0| item0.encode(env))
                    .unwrap_or_else(|| rustler::types::atom::nil().encode(env)),
                value
                    .anchor
                    .as_ref()
                    .map(|item0| encode_insertion_anchor(env, item0))
                    .unwrap_or_else(|| rustler::types::atom::nil().encode(env)),
                value.match_scope.encode(env),
            ],
        )
        .unwrap()
}
pub(crate) fn encode_create_component_ir_node<'a>(
    env: rustler::Env<'a>,
    value: &CreateComponentIRNode<'_>,
) -> rustler::Term<'a> {
    rustler::Term::map_from_arrays(
            env,
            &[
                atoms::id().encode(env),
                atoms::tag().encode(env),
                atoms::props().encode(env),
                atoms::slots().encode(env),
                atoms::asset().encode(env),
                atoms::once().encode(env),
                atoms::dynamic_slots().encode(env),
                atoms::value().encode(env),
                atoms::is_expr().encode(env),
                atoms::v_show().encode(env),
                atoms::parent().encode(env),
                atoms::anchor().encode(env),
            ],
            &[
                value.id.encode(env),
                value.tag.encode(env),
                value
                    .props
                    .iter()
                    .map(|item0| encode_ir_prop(env, item0))
                    .collect::<Vec<rustler::Term<'a>>>()
                    .encode(env),
                value
                    .slots
                    .iter()
                    .map(|item0| encode_ir_slot(env, item0))
                    .collect::<Vec<rustler::Term<'a>>>()
                    .encode(env),
                value.asset.encode(env),
                value.once.encode(env),
                value.dynamic_slots.encode(env),
                encode_component_kind(env, &value.kind),
                value
                    .is_expr
                    .as_ref()
                    .map(|item0| encode_simple_expr(env, item0))
                    .unwrap_or_else(|| rustler::types::atom::nil().encode(env)),
                value
                    .v_show
                    .as_ref()
                    .map(|item0| encode_simple_expr(env, item0))
                    .unwrap_or_else(|| rustler::types::atom::nil().encode(env)),
                value
                    .parent
                    .as_ref()
                    .map(|item0| item0.encode(env))
                    .unwrap_or_else(|| rustler::types::atom::nil().encode(env)),
                value
                    .anchor
                    .as_ref()
                    .map(|item0| encode_insertion_anchor(env, item0))
                    .unwrap_or_else(|| rustler::types::atom::nil().encode(env)),
            ],
        )
        .unwrap()
}
pub(crate) fn encode_slot_outlet_ir_node<'a>(
    env: rustler::Env<'a>,
    value: &SlotOutletIRNode<'_>,
) -> rustler::Term<'a> {
    rustler::Term::map_from_arrays(
            env,
            &[
                atoms::id().encode(env),
                atoms::name().encode(env),
                atoms::props().encode(env),
                atoms::fallback().encode(env),
                atoms::parent().encode(env),
                atoms::anchor().encode(env),
            ],
            &[
                value.id.encode(env),
                encode_simple_expr(env, &value.name),
                value
                    .props
                    .iter()
                    .map(|item0| encode_ir_prop(env, item0))
                    .collect::<Vec<rustler::Term<'a>>>()
                    .encode(env),
                value
                    .fallback
                    .as_ref()
                    .map(|item0| encode_block_ir_node(env, item0))
                    .unwrap_or_else(|| rustler::types::atom::nil().encode(env)),
                value
                    .parent
                    .as_ref()
                    .map(|item0| item0.encode(env))
                    .unwrap_or_else(|| rustler::types::atom::nil().encode(env)),
                value
                    .anchor
                    .as_ref()
                    .map(|item0| encode_insertion_anchor(env, item0))
                    .unwrap_or_else(|| rustler::types::atom::nil().encode(env)),
            ],
        )
        .unwrap()
}
pub(crate) fn encode_get_text_child_ir_node<'a>(
    env: rustler::Env<'a>,
    value: &GetTextChildIRNode,
) -> rustler::Term<'a> {
    rustler::Term::map_from_arrays(
            env,
            &[atoms::parent().encode(env)],
            &[value.parent.encode(env)],
        )
        .unwrap()
}
pub(crate) fn encode_child_ref_ir_node<'a>(
    env: rustler::Env<'a>,
    value: &ChildRefIRNode,
) -> rustler::Term<'a> {
    rustler::Term::map_from_arrays(
            env,
            &[
                atoms::child_id().encode(env),
                atoms::parent_id().encode(env),
                atoms::offset().encode(env),
            ],
            &[
                value.child_id.encode(env),
                value.parent_id.encode(env),
                value.offset.encode(env),
            ],
        )
        .unwrap()
}
pub(crate) fn encode_next_ref_ir_node<'a>(
    env: rustler::Env<'a>,
    value: &NextRefIRNode,
) -> rustler::Term<'a> {
    rustler::Term::map_from_arrays(
            env,
            &[
                atoms::child_id().encode(env),
                atoms::parent_id().encode(env),
                atoms::offset().encode(env),
            ],
            &[
                value.child_id.encode(env),
                value.prev_id.encode(env),
                value.offset.encode(env),
            ],
        )
        .unwrap()
}
pub(crate) fn encode_ir_prop<'a>(
    env: rustler::Env<'a>,
    value: &IRProp<'_>,
) -> rustler::Term<'a> {
    rustler::Term::map_from_arrays(
            env,
            &[
                atoms::key().encode(env),
                atoms::values().encode(env),
                atoms::is_component().encode(env),
                atoms::value_kind().encode(env),
            ],
            &[
                encode_simple_expr(env, &value.key),
                value
                    .values
                    .iter()
                    .map(|item0| encode_simple_expr(env, item0))
                    .collect::<Vec<rustler::Term<'a>>>()
                    .encode(env),
                value.is_component.encode(env),
                encode_prop_value_kind(env, &value.value_kind),
            ],
        )
        .unwrap()
}
pub(crate) fn encode_merged_props_source<'a>(
    env: rustler::Env<'a>,
    value: &MergedPropsSource<'_>,
) -> rustler::Term<'a> {
    match value {
        MergedPropsSource::Object(field0) => {
            rustler::Term::map_from_arrays(
                    env,
                    &[atoms::kind().encode(env), atoms::value().encode(env)],
                    &[atoms::object().encode(env), encode_simple_expr(env, field0)],
                )
                .unwrap()
        }
        MergedPropsSource::Group(field0) => {
            rustler::Term::map_from_arrays(
                    env,
                    &[atoms::kind().encode(env), atoms::value().encode(env)],
                    &[
                        atoms::group().encode(env),
                        field0
                            .iter()
                            .map(|item0| encode_ir_prop(env, item0))
                            .collect::<Vec<rustler::Term<'a>>>()
                            .encode(env),
                    ],
                )
                .unwrap()
        }
    }
}
pub(crate) fn encode_event_modifiers<'a>(
    env: rustler::Env<'a>,
    value: &EventModifiers<'_>,
) -> rustler::Term<'a> {
    rustler::Term::map_from_arrays(
            env,
            &[
                atoms::keys().encode(env),
                atoms::non_keys().encode(env),
                atoms::options().encode(env),
            ],
            &[
                value
                    .keys
                    .iter()
                    .map(|item0| (*item0).encode(env))
                    .collect::<Vec<rustler::Term<'a>>>()
                    .encode(env),
                value
                    .non_keys
                    .iter()
                    .map(|item0| (*item0).encode(env))
                    .collect::<Vec<rustler::Term<'a>>>()
                    .encode(env),
                encode_event_options(env, &value.options),
            ],
        )
        .unwrap()
}
pub(crate) fn encode_negative_branch<'a>(
    env: rustler::Env<'a>,
    value: &NegativeBranch<'_>,
) -> rustler::Term<'a> {
    match value {
        NegativeBranch::Block(field0) => {
            encode_block_ir_node(env, field0)
                .map_put(atoms::kind().encode(env), atoms::block().encode(env))
                .unwrap()
        }
        NegativeBranch::If(field0) => {
            encode_if_ir_node(env, field0)
                .map_put(atoms::kind().encode(env), atoms::if_node().encode(env))
                .unwrap()
        }
    }
}
pub(crate) fn encode_ir_slot<'a>(
    env: rustler::Env<'a>,
    value: &IRSlot<'_>,
) -> rustler::Term<'a> {
    rustler::Term::map_from_arrays(
            env,
            &[
                atoms::name().encode(env),
                atoms::fn_exp().encode(env),
                atoms::block().encode(env),
                atoms::control().encode(env),
            ],
            &[
                encode_simple_expr(env, &value.name),
                value
                    .fn_exp
                    .as_ref()
                    .map(|item0| encode_simple_expr(env, item0))
                    .unwrap_or_else(|| rustler::types::atom::nil().encode(env)),
                encode_block_ir_node(env, &value.block),
                value
                    .control
                    .as_ref()
                    .map(|item0| encode_ir_slot_control(env, item0))
                    .unwrap_or_else(|| rustler::types::atom::nil().encode(env)),
            ],
        )
        .unwrap()
}
pub(crate) fn encode_component_kind<'a>(
    env: rustler::Env<'a>,
    value: &ComponentKind,
) -> rustler::Term<'a> {
    match value {
        ComponentKind::Regular => atoms::regular().encode(env),
        ComponentKind::Teleport => atoms::teleport().encode(env),
        ComponentKind::KeepAlive => atoms::keep_alive().encode(env),
        ComponentKind::Suspense => atoms::suspense().encode(env),
        ComponentKind::Transition => atoms::transition().encode(env),
        ComponentKind::TransitionGroup => atoms::transition_group().encode(env),
        ComponentKind::Dynamic => atoms::dynamic().encode(env),
    }
}
pub(crate) fn encode_prop_value_kind<'a>(
    env: rustler::Env<'a>,
    value: &PropValueKind,
) -> rustler::Term<'a> {
    match value {
        PropValueKind::Expression => atoms::expression().encode(env),
        PropValueKind::ModelUpdate => atoms::model_update().encode(env),
        PropValueKind::ModelModifiers => atoms::model_modifiers().encode(env),
    }
}
pub(crate) fn encode_event_options<'a>(
    env: rustler::Env<'a>,
    value: &EventOptions,
) -> rustler::Term<'a> {
    rustler::Term::map_from_arrays(
            env,
            &[
                atoms::capture().encode(env),
                atoms::once().encode(env),
                atoms::passive().encode(env),
            ],
            &[
                value.capture.encode(env),
                value.once.encode(env),
                value.passive.encode(env),
            ],
        )
        .unwrap()
}
pub(crate) fn encode_ir_slot_control<'a>(
    env: rustler::Env<'a>,
    value: &IRSlotControl<'_>,
) -> rustler::Term<'a> {
    match value {
        IRSlotControl::If { condition, negative } => {
            rustler::Term::map_from_arrays(
                    env,
                    &[
                        atoms::kind().encode(env),
                        atoms::condition().encode(env),
                        atoms::negative().encode(env),
                    ],
                    &[
                        atoms::r#if().encode(env),
                        encode_simple_expr(env, condition),
                        negative
                            .as_ref()
                            .map(|item0| encode_ir_slot(env, item0))
                            .unwrap_or_else(|| rustler::types::atom::nil().encode(env)),
                    ],
                )
                .unwrap()
        }
        IRSlotControl::For(field0) => {
            encode_ir_slot_loop(env, field0)
                .map_put(atoms::kind().encode(env), atoms::r#for().encode(env))
                .unwrap()
        }
    }
}
pub(crate) fn encode_ir_slot_loop<'a>(
    env: rustler::Env<'a>,
    value: &IRSlotLoop<'_>,
) -> rustler::Term<'a> {
    rustler::Term::map_from_arrays(
            env,
            &[
                atoms::source().encode(env),
                atoms::value().encode(env),
                atoms::key().encode(env),
                atoms::index().encode(env),
                atoms::key_prop().encode(env),
            ],
            &[
                encode_simple_expr(env, &value.source),
                encode_simple_expr(env, &value.value),
                value
                    .key
                    .as_ref()
                    .map(|item0| encode_simple_expr(env, item0))
                    .unwrap_or_else(|| rustler::types::atom::nil().encode(env)),
                value
                    .index
                    .as_ref()
                    .map(|item0| encode_simple_expr(env, item0))
                    .unwrap_or_else(|| rustler::types::atom::nil().encode(env)),
                value
                    .key_prop
                    .as_ref()
                    .map(|item0| encode_simple_expr(env, item0))
                    .unwrap_or_else(|| rustler::types::atom::nil().encode(env)),
            ],
        )
        .unwrap()
}
