// This file is generated by RustQ. Do not edit by hand.

#[derive(Clone, Debug, rustler::NifMap)]
pub struct BrowserTargets {
    pub chrome: Option<u32>,
    pub firefox: Option<u32>,
    pub safari: Option<u32>,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct BundleCssOpts {
    pub minify: bool,
    pub targets: BrowserTargets,
    pub css_modules: bool,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct CompileCssOpts {
    pub minify: bool,
    pub scoped: bool,
    pub scope_id: String,
    pub filename: String,
    pub targets: BrowserTargets,
    pub css_modules: bool,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct CompileSassOpts {
    pub syntax: String,
    pub filename: String,
    pub load_paths: Vec<String>,
    pub compressed: bool,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct CompileSfcOpts {
    pub filename: String,
    pub scope_id: String,
    pub vapor: bool,
    pub ssr: bool,
    pub custom_renderer: bool,
    pub strip_types: bool,
    pub source_map: bool,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct CompileTemplateOpts {
    pub mode: String,
    pub ssr: bool,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct CompileVaporOpts {
    pub ssr: bool,
    pub diagnostics: bool,
    pub template_syntax: String,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedAttrSlot {
    pub kind: Atom,
    pub name: Option<String>,
    pub name_value: Option<String>,
    pub r#static: Option<String>,
    pub value: Option<String>,
    pub show: Option<String>,
    pub position: (usize, usize),
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedBinding {
    pub name: String,
    pub kind: String,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedComponentSlot<'a> {
    pub kind: Atom,
    pub name: String,
    pub props: Vec<EncodedProp>,
    pub events: Vec<EncodedEvent>,
    pub slots: Vec<EncodedSlotContent<'a>>,
    pub position: (usize, usize),
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedComponentUsage {
    pub name: String,
    pub props: Vec<EncodedPassedProp>,
    pub events: Vec<EncodedEventListener>,
    pub has_spread_attrs: bool,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedDiagnostic {
    pub code: Option<String>,
    pub message: String,
    pub recoverable: bool,
    pub location: Option<EncodedSourceLocation>,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedDts {
    pub dts: String,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedEvent {
    pub name: Option<String>,
    pub modifiers: Vec<String>,
    pub value: Option<String>,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedEventListener {
    pub name: String,
    pub handler: Option<String>,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedForSlot<'a> {
    pub kind: Atom,
    pub source: String,
    pub value: String,
    pub key: Option<String>,
    pub index: Option<String>,
    pub key_prop: Option<String>,
    pub block: EncodedSplitBlock<'a>,
    pub position: (usize, usize),
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedHtmlSlot {
    pub kind: Atom,
    pub value: String,
    pub position: (usize, usize),
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedIfBranch<'a> {
    pub condition: Option<String>,
    pub block: EncodedSplitBlock<'a>,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedIfSlot<'a> {
    pub kind: Atom,
    pub branches: Vec<EncodedIfBranch<'a>>,
    pub position: (usize, usize),
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedModelSlot {
    pub kind: Atom,
    pub tag: String,
    pub r#type: Option<String>,
    pub static_value: Option<String>,
    pub value: String,
    pub position: (usize, usize),
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedPassedProp {
    pub name: String,
    pub value: Option<String>,
    pub is_dynamic: bool,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedPosition {
    pub offset: u32,
    pub line: u32,
    pub column: u32,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedProp {
    pub name: Option<String>,
    pub name_value: Option<String>,
    pub r#static: Option<String>,
    pub value: Option<String>,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedPropDeclaration {
    pub name: String,
    pub required: bool,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedRange {
    pub start: u32,
    pub end: u32,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedRootAttrsSlot {
    pub kind: Atom,
    pub props: Vec<EncodedProp>,
    pub show: Option<String>,
    pub position: (usize, usize),
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedSass {
    pub code: String,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedSfcAnalysis {
    pub stats: EncodedSfcStats,
    pub bindings: Vec<EncodedBinding>,
    pub props: Vec<EncodedPropDeclaration>,
    pub emits: Vec<String>,
    pub models: Vec<String>,
    pub used_components: Vec<String>,
    pub used_directives: Vec<String>,
    pub undefined_refs: Vec<EncodedUndefinedRef>,
    pub component_usages: Vec<EncodedComponentUsage>,
    pub template_expressions: Vec<EncodedTemplateExpression>,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedSfcStats {
    pub bindings: usize,
    pub props: usize,
    pub emits: usize,
    pub models: usize,
    pub used_components: usize,
    pub used_directives: usize,
    pub undefined_refs: usize,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedSlotContent<'a> {
    pub name: Option<String>,
    pub name_value: Option<String>,
    pub params: Option<String>,
    pub block: EncodedSplitBlock<'a>,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedSlotOutlet<'a> {
    pub kind: Atom,
    pub name: Option<String>,
    pub name_value: Option<String>,
    pub props: Vec<EncodedProp>,
    pub fallback: Option<EncodedSplitBlock<'a>>,
    pub position: (usize, usize),
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedSourceLocation {
    pub start: EncodedPosition,
    pub end: EncodedPosition,
    pub source: String,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedSplitBinding {
    pub kind: Atom,
    pub name: Option<String>,
    pub modifiers: Vec<String>,
    pub value: Option<String>,
    pub at: (usize, usize),
    pub position: (usize, usize),
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedSplitBlock<'a> {
    pub statics: Vec<String>,
    pub slots: Vec<Term<'a>>,
    pub bindings: Vec<EncodedSplitBinding>,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedSplitDiagnostic {
    pub severity: Atom,
    pub message: String,
    pub start: EncodedPosition,
    pub end: EncodedPosition,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedSpreadSlot {
    pub kind: Atom,
    pub value: String,
    pub position: (usize, usize),
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedTemplateAsset {
    pub url: String,
    pub var_name: String,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedTemplateExpression {
    pub source: String,
    pub kind: String,
    pub range: EncodedRange,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedTemplateSplit<'a> {
    pub statics: Vec<String>,
    pub slots: Vec<Term<'a>>,
    pub bindings: Vec<EncodedSplitBinding>,
    pub diagnostics: Vec<EncodedSplitDiagnostic>,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedTextSlot {
    pub kind: Atom,
    pub value: String,
    pub position: (usize, usize),
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedUndefinedRef {
    pub name: String,
    pub offset: u32,
    pub context: String,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedVaporDiagnosticsOutput {
    pub code: String,
    pub templates: Vec<String>,
    pub diagnostics: Vec<EncodedDiagnostic>,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedVaporIr<'a> {
    pub templates: Vec<String>,
    pub components: Vec<String>,
    pub directives: Vec<String>,
    pub block: Term<'a>,
    pub element_template_map: Vec<(usize, usize)>,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct EncodedVaporOutput {
    pub code: String,
    pub templates: Vec<String>,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct ParseCssOpts {
    pub filename: String,
    pub custom_media: bool,
    pub css_modules: bool,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct PrintCssOpts {
    pub minify: bool,
    pub targets: BrowserTargets,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct ScopeIdOpts {
    pub root: String,
    pub production: bool,
    pub source: String,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct SplitTemplateOpts {
    pub root_attrs: bool,
}
